title: Jary Blog
description: Thoughs and notes.
email: jaroslav.henner@gmail.com
github_username:  jarovo

encoding: utf-8

# The theme Minimal requires
repository: jarovo/jarovo.github.io
remote_theme: pages-themes/minimal@v0.2.0
plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one
author: Jary
